INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1001', 'WizzAir', 1, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1002', 'WizzAir', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1003', 'Lufthansa', 0, 1, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1004', 'Lufthansa', 1, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1005', 'Lufthansa', 0, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1006', 'Lufthansa', 1, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1007', 'Windrose Aero', 1, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1008', 'Windrose Aero', 1, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1009', 'WizzAir', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1010', 'Cathay Pacific', 0, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1011', 'Cathay Pacific', 1, 1, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1012', 'Austrian Airlines', 0, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1013', 'AirAsia', 0, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1014', 'Virgin', 0, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1015', 'Virgin', 1, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1016', 'Virgin', 1, 1, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1017', 'AirAsia', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1018', 'Emirates', 1, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1019', 'Ryanair', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1020', 'AirAsia', 1, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1021', 'Windrose Aero', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1022', 'WizzAir', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1023', 'AirAsia', 1, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1024', 'AirAsia', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1025', 'Emirates', 1, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1026', 'WizzAir', 1, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1027', 'Emirates', 0, 1, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1028', 'Austrian Airlines', 0, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1029', 'Turkish Airlines', 1, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1030', 'Air France', 1, 0, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1031', 'Air France', 1, 0, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1032', 'Air France', 1, 1, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1033', 'Air France', 0, 1, 0);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1034', 'WizzAir', 0, 1, 1);
INSERT INTO `test`.`airlines` (`flightnumber`, `airline`, `additionalspaceservice`, `webregistration`, `ismealincluded`) VALUES ('1035', 'Ryanair', 0, 1, 0);